### ISSUE TITLE
2 xconf files on the same level

### ISSUE THREAD

**Issue by tuurma** [joewiz/gsh#12]
there are 2 configuration files present in gsh repo
`collection.xconf` and `replication.xconf`

as per https://github.com/joewiz/gsh/blob/master/pre-install.xql#L34 only `replication.xconf` is copied to `/db/system/config` and therefore range index configuration from `collection.xconf` is currently ineffective.

```xml
        <range>
            <create qname="territory">
                <field name="territory-id" type="xs:string" match="id"/>
            </create>
        </range>
```

Happy to merge them but I wonder what should be our naming policy here? I'd personally follow eXist-db recommended naming and have collection.xconf stay and say goodbye to replication.xconf. What do you think @joewiz?

**Comment by joewiz** [comment]
I can confirm that `gsh/collection.xconf` is not installed anywhere and thus it (or better, `replication.xconf`, as you suggest) should be deleted, although the other .xconf files that do have corresponding directories beneath `gsh/data` are successfully installed. (I believe @zwobit was the one who did the pass through all the hsg apps, ensuring replication was active on all .xconf files and  adding `replication.xconf` to the root level of apps that otherwise didn't have `collection.xconf` files affecting the root level.)
